Add noreturn show in function signature
rizinorg/rz-ghidra pull request #217
Opened 2021-03-22 18:01 UTC by Yuuoniy

**Detailed description**
Show noreturn attribute  for no return function
now the expected output like this:
```c
void sym.imp.exit noreturn (void)
{
    // WARNING: Treating indirect jump as call
    (*_reloc.dyld_stub_binder)();
    returndebug in rz_core_annotated_code_print;
}
```
**Test plan:**
seek to a noreturn function and `pdg` to see.

**Closing issue:**
closes #86 

**Testbin**
[rr.zip](https://github.com/radareorg/r2ghidra-dec/files/3670319/rr.zip)

2021-03-22 20:37 UTC, thestr4ng3r requested changes
Thanks for the pr! This is unfortunately not the right place to change the code output. It should be done in the initial code printing part before the xml even gets created. For this, you will want to look at the `PrintC` class in ghidra: https://github.com/rizinorg/ghidra/blob/master/Ghidra/Features/Decompiler/src/decompile/cpp/printc.cc
In rz-ghidra we use a subclass already to change its behavior: https://github.com/rizinorg/rz-ghidra/blob/master/src/RizinPrintC.h
If you can add the noreturn just by overriding a function in `RizinPrintC` without duplicating a significant amount of code from ghidra, adding it here would be good, otherwise you can send a pr to https://github.com/rizinorg/ghidra to change it in `PrintC`.

2021-03-23 06:37 UTC, Yuuoniy commented
OK, I have taken a look at `PrintC`,  ghidra uses different emit functions to output every part of a function，eg. https://github.com/rizinorg/ghidra/blob/master/Ghidra/Features/Decompiler/src/decompile/cpp/printc.cc#L2289  used to generate FunctionDeclaration.  So my first idea is add a noreturn node when generating XML based on `FuncProto.isNoreturn` attribute.
How about this?

2021-03-23 09:38 UTC, thestr4ng3r commented
Yes, this looks good. Now please update the ghidra submodule on rz-ghidra side here and add a test case to https://github.com/rizinorg/rz-ghidra/blob/master/test/db/extras/ghidra, ideally on top of an existing binary from https://github.com/rizinorg/rizin-testbins

2021-03-23 11:18 UTC, Yuuoniy commented
I've updated.

2021-03-23 11:19 UTC, thestr4ng3r approved these changes
Perfect, thanks!

2021-03-23 11:19 UTC, merged